name: Deploy Multiple Apps to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout
      - uses: actions/checkout@v3

      # 2️⃣ Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Build Next.js app
      - name: Build Next.js app
        run: |
          cd my-portofolio
          npm ci
          npm run build   # next build génère automatiquement out/

      # 4️⃣ Déploiement GitHub Pages
      - name: Deploy apps to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: |
            my-portofolio/out
            nj-test-website
          destination_dir: |
            my-portofolio
            nj-test-website
